/* ---------- county names ---------- */
// ornitho.de gives a place's county as "<state>/<code>" (from "Gemeinde (SN, GR)"). The codes follow
// ornitho's own county list, mostly vehicle registration prefixes: a "*" marks the district around a
// city of the same code (A = Augsburg, A* = Landkreis Augsburg), and Mecklenburg-Vorpommern and parts
// of Niedersachsen keep the districts from before their reforms. Unknown codes show as the bare code
// (see countyName()).
const COUNTIES = Object.fromEntries(Object.entries({
  BW: "AA:Ostalbkreis BAD:Baden-Baden BB:Böblingen BC:Biberach BL:Zollernalbkreis CW:Calw EM:Emmendingen ES:Esslingen FDS:Freudenstadt FN:Bodenseekreis FR:Freiburg im Breisgau FR*:Breisgau-Hochschwarzwald GP:Göppingen HD:Heidelberg HD*:Rhein-Neckar-Kreis HDH:Heidenheim HN:Heilbronn HN*:Landkreis Heilbronn KA:Karlsruhe KA*:Landkreis Karlsruhe KN:Konstanz KÜN:Hohenlohekreis LB:Ludwigsburg LÖ:Lörrach MA:Mannheim MOS:Neckar-Odenwald-Kreis OG:Ortenaukreis PF:Pforzheim PF*:Enzkreis RA:Rastatt RT:Reutlingen RV:Ravensburg RW:Rottweil S:Stuttgart SHA:Schwäbisch Hall SIG:Sigmaringen TBB:Main-Tauber-Kreis TUT:Tuttlingen TÜ:Tübingen UL:Ulm UL*:Alb-Donau-Kreis VS:Schwarzwald-Baar-Kreis WN:Rems-Murr-Kreis WT:Waldshut",
  BY: "A:Augsburg A*:Landkreis Augsburg AB:Aschaffenburg AB*:Landkreis Aschaffenburg AIC:Aichach-Friedberg AM:Amberg AN:Ansbach AN*:Landkreis Ansbach AS:Amberg-Sulzbach AÖ:Altötting BA:Bamberg BA*:Landkreis Bamberg BGL:Berchtesgadener Land BT:Bayreuth BT*:Landkreis Bayreuth CHA:Cham CO:Coburg CO*:Landkreis Coburg DAH:Dachau DEG:Deggendorf DGF:Dingolfing-Landau DLG:Dillingen an der Donau DON:Donau-Ries EBE:Ebersberg ED:Erding EI:Eichstätt ER:Erlangen ERH:Erlangen-Höchstadt FFB:Fürstenfeldbruck FO:Forchheim FRG:Freyung-Grafenau FS:Freising FÜ:Fürth FÜ*:Landkreis Fürth GAP:Garmisch-Partenkirchen GZ:Günzburg HAS:Haßberge HO:Hof HO*:Landkreis Hof IN:Ingolstadt KC:Kronach KE:Kempten (Allgäu) KEH:Kelheim KF:Kaufbeuren KG:Bad Kissingen KT:Kitzingen KU:Kulmbach LA:Landshut LA*:Landkreis Landshut LAU:Nürnberger Land LI:Lindau (Bodensee) LIF:Lichtenfels LL:Landsberg am Lech M:München M*:Landkreis München MB:Miesbach MIL:Miltenberg MM:Memmingen MN:Unterallgäu MSP:Main-Spessart MÜ:Mühldorf am Inn N:Nürnberg ND:Neuburg-Schrobenhausen NEA:Neustadt an der Aisch-Bad Windsheim NES:Rhön-Grabfeld NEW:Neustadt an der Waldnaab NM:Neumarkt in der Oberpfalz NU:Neu-Ulm OA:Oberallgäu OAL:Ostallgäu PA:Passau PA*:Landkreis Passau PAF:Pfaffenhofen an der Ilm PAN:Rottal-Inn R:Regensburg R*:Landkreis Regensburg REG:Regen RH:Roth RO:Rosenheim RO*:Landkreis Rosenheim SAD:Schwandorf SC:Schwabach SR:Straubing SR*:Straubing-Bogen STA:Starnberg SW:Schweinfurt SW*:Landkreis Schweinfurt TIR:Tirschenreuth TS:Traunstein TÖL:Bad Tölz-Wolfratshausen WEN:Weiden in der Oberpfalz WM:Weilheim-Schongau WUG:Weißenburg-Gunzenhausen WUN:Wunsiedel im Fichtelgebirge WÜ:Würzburg WÜ*:Landkreis Würzburg",
  BE: "B:Berlin",
  BB: "BAR:Barnim BRB:Brandenburg an der Havel CB:Cottbus EE:Elbe-Elster FF:Frankfurt (Oder) HVL:Havelland LDS:Dahme-Spreewald LOS:Oder-Spree MOL:Märkisch-Oderland OHV:Oberhavel OPR:Ostprignitz-Ruppin OSL:Oberspreewald-Lausitz P:Potsdam PM:Potsdam-Mittelmark PR:Prignitz SPN:Spree-Neiße TF:Teltow-Fläming UM:Uckermark",
  HB: "HB:Bremen HBh:Bremerhaven",
  HH: "HH:Hamburg",
  HE: "DA:Darmstadt DA*:Darmstadt-Dieburg ERB:Odenwaldkreis ESW:Werra-Meißner-Kreis F*:Frankfurt am Main FB:Wetteraukreis FD:Fulda GG:Groß-Gerau GI:Gießen HEF:Hersfeld-Rotenburg HG:Hochtaunuskreis HP:Bergstraße HR:Schwalm-Eder-Kreis KB:Waldeck-Frankenberg KS:Kassel KS*:Landkreis Kassel LDK:Lahn-Dill-Kreis LM:Limburg-Weilburg MKK:Main-Kinzig-Kreis MR:Marburg-Biedenkopf MTK:Main-Taunus-Kreis OF:Offenbach am Main OF*:Landkreis Offenbach RÜD:Rheingau-Taunus-Kreis VB:Vogelsbergkreis WI:Wiesbaden",
  MV: "DBR:Bad Doberan DM:Demmin GÜ:Güstrow HGW:Greifswald HRO:Rostock HST:Stralsund HWI:Wismar LWL:Ludwigslust MST:Mecklenburg-Strelitz MÜR:Müritz NB:Neubrandenburg NVP:Nordvorpommern NWM:Nordwestmecklenburg OVP:Ostvorpommern PCH:Parchim RÜG:Rügen SN:Schwerin UER:Uecker-Randow",
  NI: "AUR:Aurich BRA:Wesermarsch BS:Braunschweig CE:Celle CLP:Cloppenburg CUX:Cuxhaven DAN:Lüchow-Dannenberg DEL:Delmenhorst DH:Diepholz EL:Emsland EMD:Emden FRI:Friesland GF:Gifhorn GS:Goslar GÖ:Göttingen H:Region Hannover HE:Helmstedt HI:Hildesheim HK:Heidekreis HM:Hameln-Pyrmont HOL:Holzminden LER:Leer LG:Lüneburg NI:Nienburg (Weser) NOH:Grafschaft Bentheim NOM:Northeim OHA:Osterode am Harz OHZ:Osterholz OL:Oldenburg OL*:Landkreis Oldenburg OS:Osnabrück OS*:Landkreis Osnabrück PE:Peine ROW:Rotenburg (Wümme) SHG:Schaumburg STD:Stade SZ:Salzgitter UE:Uelzen VEC:Vechta VER:Verden WF:Wolfenbüttel WHV:Wilhelmshaven WL:Harburg WOB:Wolfsburg WST:Ammerland WTM:Wittmund",
  NW: "AC:Aachen AC*:Städteregion Aachen BI:Bielefeld BM:Rhein-Erft-Kreis BN:Bonn BO:Bochum BOR:Borken BOT:Bottrop COE:Coesfeld D:Düsseldorf DN:Düren DO:Dortmund DU:Duisburg E:Essen EN:Ennepe-Ruhr-Kreis EU:Euskirchen GE:Gelsenkirchen GL:Rheinisch-Bergischer Kreis GM:Oberbergischer Kreis GT:Gütersloh HA:Hagen HAM:Hamm HER:Herne HF:Herford HS:Heinsberg HSK:Hochsauerlandkreis HX:Höxter K:Köln KLE:Kleve KR:Krefeld LEV:Leverkusen LIP:Lippe ME:Mettmann MG:Mönchengladbach MH:Mülheim an der Ruhr MI:Minden-Lübbecke MK:Märkischer Kreis MS:Münster NE:Rhein-Kreis Neuss OB:Oberhausen OE:Olpe PB:Paderborn RE:Recklinghausen RS:Remscheid SG:Solingen SI:Siegen-Wittgenstein SO:Soest ST:Steinfurt SU:Rhein-Sieg-Kreis UN:Unna VIE:Viersen W:Wuppertal WAF:Warendorf WES:Wesel",
  RP: "AK:Altenkirchen AW:Ahrweiler AZ:Alzey-Worms BIR:Birkenfeld BIT:Eifelkreis Bitburg-Prüm COC:Cochem-Zell DAU:Vulkaneifel DÜW:Bad Dürkheim EMS:Rhein-Lahn-Kreis FT:Frankenthal GER:Germersheim KH:Bad Kreuznach KIB:Donnersbergkreis KL:Kaiserslautern KL*:Landkreis Kaiserslautern KO:Koblenz KUS:Kusel LD:Landau in der Pfalz LU:Ludwigshafen am Rhein MYK:Mayen-Koblenz MZ:Mainz MZ*:Mainz-Bingen NR:Neuwied NW:Neustadt an der Weinstraße PS:Pirmasens PS*:Südwestpfalz RP:Rhein-Pfalz-Kreis SIM:Rhein-Hunsrück-Kreis SP:Speyer SÜW:Südliche Weinstraße TR:Trier TR*:Trier-Saarburg WIL:Bernkastel-Wittlich WO:Worms WW:Westerwaldkreis ZW:Zweibrücken",
  SL: "HOM:Saarpfalz-Kreis MZG:Merzig-Wadern NK:Neunkirchen SB:Regionalverband Saarbrücken SLS:Saarlouis WND:St. Wendel",
  SN: "BZ:Bautzen C:Chemnitz DD:Dresden ERZ:Erzgebirgskreis FG:Mittelsachsen GR:Görlitz L:Leipzig L*:Landkreis Leipzig MEI:Meißen PIR:Sächsische Schweiz-Osterzgebirge TDO:Nordsachsen V:Vogtlandkreis Z:Zwickau",
  ST: "ABI:Anhalt-Bitterfeld BK:Börde BLK:Burgenlandkreis DE:Dessau-Roßlau HAL:Halle (Saale) HZ:Harz JL:Jerichower Land MD:Magdeburg MSH:Mansfeld-Südharz SAW:Altmarkkreis Salzwedel SDL:Stendal SK:Saalekreis SLK:Salzlandkreis WB:Wittenberg",
  SH: "FL:Flensburg HEI:Dithmarschen HL:Lübeck IZ:Steinburg KI:Kiel NF:Nordfriesland NMS:Neumünster OD:Stormarn OH:Ostholstein PI:Pinneberg PLÖ:Plön RD:Rendsburg-Eckernförde RZ:Herzogtum Lauenburg SE:Segeberg SL:Schleswig-Flensburg",
  TH: "ABG:Altenburger Land AP:Weimarer Land EA:Eisenach EF:Erfurt EIC:Eichsfeld G:Gera GRZ:Greiz GTH:Gotha HBN:Hildburghausen IK:Ilm-Kreis J:Jena KYF:Kyffhäuserkreis NDH:Nordhausen SHK:Saale-Holzland-Kreis SHL:Suhl SLF:Saalfeld-Rudolstadt SM:Schmalkalden-Meiningen SOK:Saale-Orla-Kreis SON:Sonneberg SÖM:Sömmerda UH:Unstrut-Hainich-Kreis WAK:Wartburgkreis WE:Weimar",
  LU: "LUX:Luxemburg",
  // entries are "CODE:Name" separated by spaces, and names may contain spaces too: split before every "CODE:"
}).flatMap(([state, list]) => list.split(/ (?=[A-ZÄÖÜ][A-ZÄÖÜa-z]*\*?:)/).map(entry => {
  const [code, name] = entry.split(/:(.*)/s);
  return [`${state}/${code}`, name];
})));
// the offshore areas (Ausschließliche Wirtschaftszone) of ornitho's list, whatever state a record gives with them
const SEA_AREAS = { ASH: "AWZ Ostsee (SH-Teil)", AMV: "AWZ Ostsee (MV-Teil)", AWN: "AWZ Nordsee" };
