/* ---------- county names ---------- */
// ornitho.de gives a place's county as "<state>/<code>" (from "Gemeinde (SN, GR)"), where the code is
// the district's vehicle registration prefix. Where a city and the district around it share a prefix
// (e.g. L, M, KS), both show the city's name. Unknown codes fall back to the bare code (see countyName()).
const COUNTIES = Object.fromEntries(Object.entries({
  SH: "FL:Flensburg KI:Kiel HL:Lübeck NMS:Neumünster HEI:Dithmarschen RZ:Herzogtum Lauenburg NF:Nordfriesland OH:Ostholstein PI:Pinneberg PLÖ:Plön RD:Rendsburg-Eckernförde SL:Schleswig-Flensburg SE:Segeberg IZ:Steinburg OD:Stormarn",
  HH: "HH:Hamburg",
  HB: "HB:Bremen BHV:Bremerhaven",
  BE: "B:Berlin",
  NI: "BS:Braunschweig SZ:Salzgitter WOB:Wolfsburg GF:Gifhorn GS:Goslar HE:Helmstedt NOM:Northeim PE:Peine WF:Wolfenbüttel GÖ:Göttingen H:Region Hannover DH:Diepholz HM:Hameln-Pyrmont HI:Hildesheim HOL:Holzminden NI:Nienburg (Weser) SHG:Schaumburg CE:Celle CUX:Cuxhaven HK:Heidekreis LG:Lüneburg OHZ:Osterholz ROW:Rotenburg (Wümme) STD:Stade UE:Uelzen VER:Verden WL:Harburg DAN:Lüchow-Dannenberg DEL:Delmenhorst EMD:Emden OL:Oldenburg OS:Osnabrück WHV:Wilhelmshaven AUR:Aurich CLP:Cloppenburg EL:Emsland FRI:Friesland NOH:Grafschaft Bentheim LER:Leer VEC:Vechta BRA:Wesermarsch WTM:Wittmund",
  NW: "D:Düsseldorf DU:Duisburg E:Essen KR:Krefeld MG:Mönchengladbach MH:Mülheim an der Ruhr OB:Oberhausen RS:Remscheid SG:Solingen W:Wuppertal KLE:Kleve ME:Mettmann NE:Rhein-Kreis Neuss VIE:Viersen WES:Wesel BN:Bonn K:Köln LEV:Leverkusen AC:Städteregion Aachen DN:Düren BM:Rhein-Erft-Kreis EU:Euskirchen HS:Heinsberg GM:Oberbergischer Kreis GL:Rheinisch-Bergischer Kreis SU:Rhein-Sieg-Kreis BOT:Bottrop GE:Gelsenkirchen MS:Münster BOR:Borken COE:Coesfeld RE:Recklinghausen ST:Steinfurt WAF:Warendorf BI:Bielefeld GT:Gütersloh HF:Herford HX:Höxter LIP:Lippe MI:Minden-Lübbecke PB:Paderborn BO:Bochum DO:Dortmund HA:Hagen HAM:Hamm HER:Herne EN:Ennepe-Ruhr-Kreis HSK:Hochsauerlandkreis MK:Märkischer Kreis OE:Olpe SI:Siegen-Wittgenstein SO:Soest UN:Unna",
  HE: "DA:Darmstadt F:Frankfurt am Main OF:Offenbach WI:Wiesbaden HP:Bergstraße DI:Darmstadt-Dieburg GG:Groß-Gerau HG:Hochtaunuskreis MKK:Main-Kinzig-Kreis MTK:Main-Taunus-Kreis ERB:Odenwaldkreis RÜD:Rheingau-Taunus-Kreis FB:Wetteraukreis GI:Gießen LDK:Lahn-Dill-Kreis LM:Limburg-Weilburg MR:Marburg-Biedenkopf VB:Vogelsbergkreis KS:Kassel FD:Fulda HEF:Hersfeld-Rotenburg KB:Waldeck-Frankenberg HR:Schwalm-Eder-Kreis ESW:Werra-Meißner-Kreis",
  RP: "KO:Koblenz AK:Altenkirchen AW:Ahrweiler BIR:Birkenfeld COC:Cochem-Zell EMS:Rhein-Lahn-Kreis KH:Bad Kreuznach MYK:Mayen-Koblenz NR:Neuwied SIM:Rhein-Hunsrück-Kreis WW:Westerwaldkreis TR:Trier BIT:Eifelkreis Bitburg-Prüm DAU:Vulkaneifel WIL:Bernkastel-Wittlich FT:Frankenthal KL:Kaiserslautern LD:Landau in der Pfalz LU:Ludwigshafen am Rhein MZ:Mainz NW:Neustadt an der Weinstraße PS:Pirmasens SP:Speyer WO:Worms ZW:Zweibrücken AZ:Alzey-Worms DÜW:Bad Dürkheim KIB:Donnersbergkreis GER:Germersheim KUS:Kusel SÜW:Südliche Weinstraße RP:Rhein-Pfalz-Kreis",
  BW: "S:Stuttgart BB:Böblingen ES:Esslingen GP:Göppingen LB:Ludwigsburg WN:Rems-Murr-Kreis HN:Heilbronn KÜN:Hohenlohekreis SHA:Schwäbisch Hall TBB:Main-Tauber-Kreis HDH:Heidenheim AA:Ostalbkreis BAD:Baden-Baden KA:Karlsruhe RA:Rastatt HD:Heidelberg MA:Mannheim MOS:Neckar-Odenwald-Kreis PF:Pforzheim CW:Calw FDS:Freudenstadt FR:Freiburg im Breisgau EM:Emmendingen OG:Ortenaukreis RW:Rottweil VS:Schwarzwald-Baar-Kreis TUT:Tuttlingen KN:Konstanz LÖ:Lörrach WT:Waldshut RT:Reutlingen TÜ:Tübingen BL:Zollernalbkreis UL:Ulm BC:Biberach FN:Bodenseekreis RV:Ravensburg SIG:Sigmaringen",
  BY: "M:München A:Augsburg N:Nürnberg R:Regensburg IN:Ingolstadt WÜ:Würzburg ER:Erlangen FÜ:Fürth BA:Bamberg BT:Bayreuth CO:Coburg HO:Hof AB:Aschaffenburg SW:Schweinfurt KE:Kempten (Allgäu) KF:Kaufbeuren MM:Memmingen LA:Landshut PA:Passau SR:Straubing AM:Amberg WEN:Weiden in der Oberpfalz RO:Rosenheim AIC:Aichach-Friedberg AÖ:Altötting AS:Amberg-Sulzbach AN:Ansbach BGL:Berchtesgadener Land CHA:Cham DAH:Dachau DEG:Deggendorf DLG:Dillingen an der Donau DGF:Dingolfing-Landau DON:Donau-Ries EBE:Ebersberg ED:Erding EI:Eichstätt ERH:Erlangen-Höchstadt FO:Forchheim FS:Freising FRG:Freyung-Grafenau FFB:Fürstenfeldbruck GAP:Garmisch-Partenkirchen GZ:Günzburg HAS:Haßberge KEH:Kelheim KG:Bad Kissingen KC:Kronach KT:Kitzingen KU:Kulmbach LAU:Nürnberger Land LI:Lindau (Bodensee) LIF:Lichtenfels LL:Landsberg am Lech MB:Miesbach MIL:Miltenberg MN:Unterallgäu MÜ:Mühldorf am Inn MSP:Main-Spessart ND:Neuburg-Schrobenhausen NEA:Neustadt an der Aisch-Bad Windsheim NES:Rhön-Grabfeld NEW:Neustadt an der Waldnaab NM:Neumarkt in der Oberpfalz NU:Neu-Ulm OA:Oberallgäu OAL:Ostallgäu PAF:Pfaffenhofen an der Ilm PAN:Rottal-Inn REG:Regen RH:Roth SAD:Schwandorf STA:Starnberg TIR:Tirschenreuth TÖL:Bad Tölz-Wolfratshausen TS:Traunstein WM:Weilheim-Schongau WUG:Weißenburg-Gunzenhausen WUN:Wunsiedel im Fichtelgebirge",
  SL: "SB:Regionalverband Saarbrücken MZG:Merzig-Wadern NK:Neunkirchen SLS:Saarlouis HOM:Saarpfalz-Kreis WND:St. Wendel",
  BB: "P:Potsdam BRB:Brandenburg an der Havel CB:Cottbus FF:Frankfurt (Oder) BAR:Barnim LDS:Dahme-Spreewald EE:Elbe-Elster HVL:Havelland MOL:Märkisch-Oderland OHV:Oberhavel OSL:Oberspreewald-Lausitz LOS:Oder-Spree OPR:Ostprignitz-Ruppin PM:Potsdam-Mittelmark PR:Prignitz SPN:Spree-Neiße TF:Teltow-Fläming UM:Uckermark",
  MV: "HRO:Rostock SN:Schwerin LRO:Landkreis Rostock LUP:Ludwigslust-Parchim MSE:Mecklenburgische Seenplatte NWM:Nordwestmecklenburg VG:Vorpommern-Greifswald VR:Vorpommern-Rügen",
  SN: "C:Chemnitz DD:Dresden L:Leipzig BZ:Bautzen ERZ:Erzgebirgskreis GR:Görlitz MEI:Meißen FG:Mittelsachsen TDO:Nordsachsen PIR:Sächsische Schweiz-Osterzgebirge V:Vogtlandkreis Z:Zwickau",
  ST: "DE:Dessau-Roßlau HAL:Halle (Saale) MD:Magdeburg SAW:Altmarkkreis Salzwedel ABI:Anhalt-Bitterfeld BK:Börde BLK:Burgenlandkreis HZ:Harz JL:Jerichower Land MSH:Mansfeld-Südharz SK:Saalekreis SLK:Salzlandkreis SDL:Stendal WB:Wittenberg",
  TH: "EF:Erfurt G:Gera J:Jena SHL:Suhl WE:Weimar EA:Eisenach EIC:Eichsfeld GTH:Gotha GRZ:Greiz HBN:Hildburghausen IK:Ilm-Kreis KYF:Kyffhäuserkreis NDH:Nordhausen SHK:Saale-Holzland-Kreis SOK:Saale-Orla-Kreis SLF:Saalfeld-Rudolstadt SM:Schmalkalden-Meiningen SON:Sonneberg UH:Unstrut-Hainich-Kreis AP:Weimarer Land WAK:Wartburgkreis ABG:Altenburger Land SÖM:Sömmerda",
  // the codes are separated by spaces, but names may contain spaces too: split before every "CODE:"
}).flatMap(([state, list]) => list.split(/ (?=[A-ZÄÖÜ]+:)/).map(entry => {
  const [code, name] = entry.split(/:(.*)/s);
  return [`${state}/${code}`, name];
})));
